# Generated by Django 4.0.3 on 2023-08-11 12:07

import USERS.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', USERS.manager.UserManager()),
            ],
        ),
    ]
